# Generated by Django 5.0.6 on 2024-06-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('guests', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
